### ISSUE TITLE
TypeError: 'TextIter' object is not iterable with Plugin

### ISSUE THREAD

**Issue by contradictioned** [isamert/gracer#7]
Anytime I open a rust file the following error is printed to the console:

```
Traceback (most recent call last):
  File "/home/manuel/.local/share/gedit/plugins/gracer/gracer.py", line 237, in do_match
    _, iter = context.get_iter()
TypeError: 'TextIter' object is not iterable
```

I have installed gracer as suggested via git pull into this directory. My system:
- gedit 3.14.0
- Debian 8.6 64
- Python2 2.7.9 and Python3.4.2 installed via normal package manager

Any thoughts?

**Comment by isamert** [comment]
Can you try this branch? I made some changes that can solve this problem.
https://github.com/isamert/gracer/tree/iter-fix

**Comment by contradictioned** [comment]
Yes, this does the trick! 😄

**Comment by isamert** [comment]
Can you try master branch now? I made a couple changes and I can't test if it works or not on your setup.

**Comment by contradictioned** [comment]
Okay, maybe I was too quick with the last response.

What works is now the following: Autocompletion with `use std::...` and methods on structs from the standard library and for structs, variables, ... defined in the same file.

When I use structs from a file that belongs to the same cargo project (`mod otherfile`), no code completion happens (which it does in Sublime for the same test files with its plugin for racer).

Also, when I use "Find Definition", it works for tokens defined in the same file; but for the standard library gedit just dies with:

```
(gedit:13027): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.14.5/./gtk/gtktextbtree.c:4097: char offset off the end of the line

(gedit:13027): Gtk-ERROR **: Char offset 11 is off the end of the line
[1]    13027 trace trap  gedit
```

and for things from a different file it says:

```
'NoneType' object is not subscriptable
```

**Comment by isamert** [comment]
Now it should complete for cargo projects. I couldn't get the error you got from "Find Definition". Is it still happening?

**Comment by isamert** [comment]
Now everything should work as expected. It should complete for cargo projects and find definition should open the related file in new tab. Can you confirm please?

**Comment by contradictioned** [comment]
Confirmed!
Find definition and completion works with Rust sources and own modules.
It opens for me in a new window (not a new tab), but this might be only configuration issue on my side.

**Comment by isamert** [comment]
Actually, I have that "new window" problem too, but the function I used for this clearly states that it opens in a new tab but it does not. I'll try to fix it.
